# Conclusiones

El análisis de series de tiempo realizado a lo largo de este documento permite evidenciar que los precios de la ahuyama, la cebolla junca, habichuela y tomate chonto tienen algunos atributos como estacionalidad compuesta,es decir, el periodo bajo el cual se repiten algunos patrones temporales no es fijo o regular sino que puede variar,  adicionalmente es posible apreciar que ninguna de las series es estacionaria y además en términos generales todas las series presentan periodos de alta volatilidad despues del año 2020 alcanzando inclusive momentos de máximos históricos. Los atributos de las series de tiempo analizadas llevan a que los modelos lineales tradicionales como el modelo ARIMA no sean los más efectivos para realizar un pronóstico ajustado, en contraste a esto los modelos no lineales como el suavizamiento exponencial presentan procesos de ajuste favorables y que emulan de manera eficiente la estacionalidad de las series de tiempo, sin embargo es preciso aclarar que en el marco de este ejercicio se ha probado solo una configuración por modelo, por lo tanto vale la pena explorar otras combinaciones de hiperparámetros en otros modelos con el fin de poder determinar si definitivamente modelos como el suavizamiento exponencial triple realmente se perfilan como el modelo más adecuado para este tipo de serie. 


